### ISSUE TITLE
binder link appears broken

### ISSUE THREAD

**Issue by mathematicalmichael** [binder-examples/bokeh#1]
binder builds and launches but only a white screen shows up

**Comment by choldgraf** [comment]
Hmmm, I wonder if the bokeh server got updated and something now messes up? I'll try triggering a re-build and we'll see if that fixes things

**Comment by choldgraf** [comment]
I think this is now fixed - the issue was that we were pinning to `nbserverproxy` while it had actually been changed to `jupyter-server-proxy` so we weren't getting udpates

**Comment by mathematicalmichael** [comment]
Wow awesome, thank you for the rapid response
